# Generated by Django 5.0.1 on 2024-01-18 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remove_candidate_person_ptr_candidate_person_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Nombre de Usuario')),
                ('date_joined', models.DateTimeField()),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si el usuario pertenece a la mesa electoral', verbose_name='Es de la mesa electoral?')),
                ('is_superuser', models.BooleanField(default=False, help_text='Indica si el usuario tiene power', verbose_name='Es super usuario?')),
                ('election_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.person')),
            ],
        ),
    ]
