# Generated by Django 5.0.1 on 2024-01-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_customuser_exp_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ci',
            new_name='person',
        ),
    ]
