version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
    - DJANGO_SETTINGS_MODULE=sigef_backend.settings
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    env_file:
      - ./.env

