version: "3"
services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: sigef_postgres
    # container_name: school_management_postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data  # Agrega esta definición de volumen
      - postgres_backup_local:/backups
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  web: &web
    build:
      context: .
      dockerfile: compose/local/Dockerfile  # Asegúrate de que esto sea correcto.
    image: sigef_image
    env_file:
      - ./.env
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"

networks:
  default:
    external:
      name: sigef_local_network

volumes:
  postgres_data_local: { }
  postgres_backup_local: { }
