# Generated by Django 5.0.1 on 2024-01-10 20:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ci', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('institution', 'Institución'), ('campus', 'Sede'), ('faculty', 'Facultad')], max_length=20)),
                ('location_id', models.IntegerField()),
                ('council_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(3)])),
                ('voting_date', models.DateTimeField(validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)])),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElectorRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.person')),
                ('election_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
            ],
            options={
                'db_table': 'elector_registry',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.faculty'),
        ),
        migrations.AddField(
            model_name='campus',
            name='institution_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.institution'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elections.person')),
                ('biography', models.TextField(blank=True, help_text='Introduzca la biografía del candidato.', null=True, verbose_name='Biografía')),
                ('who_added', models.CharField(choices=[('committee', 'Comité'), ('elector', 'Elector')], max_length=20)),
                ('staff_votes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('president_votes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('election_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
            ],
            bases=('elections.person',),
        ),
        migrations.AddConstraint(
            model_name='electorregistry',
            constraint=models.UniqueConstraint(fields=('ci', 'election_id'), name='unique_elector_registry'),
        ),
    ]
