# Generated by Django 5.0.1 on 2024-01-18 04:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='person_ptr',
        ),
        migrations.AddField(
            model_name='candidate',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidate', serialize=False, to='elections.person'),
        ),
        migrations.CreateModel(
            name='CandidateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, help_text='Introduzca la biografía del candidato.', null=True, verbose_name='Biografía')),
                ('who_added', models.CharField(choices=[('committee', 'Comité'), ('elector', 'Elector')], max_length=20)),
                ('staff_votes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('president_votes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('election_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_log', to='elections.person')),
            ],
        ),
    ]
