# Generated by Django 5.0.1 on 2024-01-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='person_ptr',
        ),
        migrations.AddField(
            model_name='candidate',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidate', serialize=False, to='elections.person'),
        ),
    ]
